/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.uni.view;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import proyecto.uni.controller.DatosGenerales;
import proyecto.uni.model.Tasa;
import proyecto.uni.model.Validar;

/**
 *
 * @author HP14
 */
public class ConvTasa extends javax.swing.JFrame {

    /**
     * Creates new form ConvTasa
     */
    private List<Double> textFieldTasa;
    private DatosGenerales datos;
    private Tasa tasa;
    private DecimalFormat df;
    private Validar validar;

    public ConvTasa() {
        initComponents();
        textFieldTasa = new ArrayList<>();
        datos = new DatosGenerales();
        txtTasaEfectivaiE.disable();
        txtTasaEquivalente.disable();
        tasaNominalU.disable();
        tasa = new Tasa();
        df = new DecimalFormat("##.##");
        validar = new Validar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        btnCalcularTasaEfectiva = new javax.swing.JButton();
        txtTasaEfectivaiE = new javax.swing.JFormattedTextField();
        txtFrecuenciaCapitalizacionE = new javax.swing.JFormattedTextField();
        txtTasaNominaljE = new javax.swing.JFormattedTextField();
        btnSalir1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        btnCalcularTasaNominal = new javax.swing.JButton();
        tasaNominalU = new javax.swing.JFormattedTextField();
        tasaEfectivaU = new javax.swing.JFormattedTextField();
        frecuenciaU = new javax.swing.JFormattedTextField();
        btnSalir2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        btnCalcularTasaEquivalente = new javax.swing.JButton();
        txtTasaEquivalente = new javax.swing.JFormattedTextField();
        txtTasaNominalEq = new javax.swing.JFormattedTextField();
        txtFrecuenciaEq = new javax.swing.JFormattedTextField();
        txtCapitalizacionEq = new javax.swing.JFormattedTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(187, 225, 250));

        jPanel1.setBackground(new java.awt.Color(254, 250, 236));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel36.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Tasa efectiva (i) ");

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Tasa efectiva (i) =");

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Tasa nominal (j) =");

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Frecuencia de capitalizacion (m) =");

        jComboBox5.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox5.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Trimestral", "Cuatrimestral", "Bimestral", "Diario 360", "Diario 365" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        btnCalcularTasaEfectiva.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcularTasaEfectiva.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcularTasaEfectiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/icons8-calculate-48.png"))); // NOI18N
        btnCalcularTasaEfectiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTasaEfectivaActionPerformed(evt);
            }
        });

        txtTasaEfectivaiE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        txtTasaEfectivaiE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTasaEfectivaiEKeyTyped(evt);
            }
        });

        txtFrecuenciaCapitalizacionE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtFrecuenciaCapitalizacionE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrecuenciaCapitalizacionEActionPerformed(evt);
            }
        });
        txtFrecuenciaCapitalizacionE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrecuenciaCapitalizacionEKeyTyped(evt);
            }
        });

        txtTasaNominaljE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        txtTasaNominaljE.setToolTipText("ingresar % al final");
        txtTasaNominaljE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTasaNominaljEActionPerformed(evt);
            }
        });
        txtTasaNominaljE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTasaNominaljEKeyTyped(evt);
            }
        });

        btnSalir1.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir1.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/icons8-emergency-exit-50.png"))); // NOI18N
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(0, 124, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrecuenciaCapitalizacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTasaEfectivaiE, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTasaNominaljE, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCalcularTasaEfectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTasaEfectivaiE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTasaNominaljE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrecuenciaCapitalizacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcularTasaEfectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tasa Efectiva", jPanel1);

        jPanel3.setBackground(new java.awt.Color(254, 250, 236));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel45.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Tasa nominal (j) ");

        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Tasa nominal (j) =");

        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Tasa efectiva (i) =");

        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Frecuencia de capitalizacion (m) =");

        jComboBox8.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox8.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Trimestral", "Cuatrimestral", "Bimestral", "Diario 360", "Diario 365" }));

        btnCalcularTasaNominal.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcularTasaNominal.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcularTasaNominal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/icons8-calculate-48.png"))); // NOI18N
        btnCalcularTasaNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTasaNominalActionPerformed(evt);
            }
        });

        tasaNominalU.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));

        tasaEfectivaU.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        tasaEfectivaU.setToolTipText("ingresar % al final");
        tasaEfectivaU.setPreferredSize(new java.awt.Dimension(142, 20));
        tasaEfectivaU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tasaEfectivaUKeyTyped(evt);
            }
        });

        frecuenciaU.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        frecuenciaU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                frecuenciaUKeyTyped(evt);
            }
        });

        btnSalir2.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir2.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/icons8-emergency-exit-50.png"))); // NOI18N
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addGap(161, 161, 161))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcularTasaNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel46)
                        .addComponent(jLabel47)
                        .addComponent(jLabel48)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tasaNominalU)
                        .addComponent(tasaEfectivaU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(frecuenciaU, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSalir2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(tasaNominalU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(tasaEfectivaU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(frecuenciaU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcularTasaNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        jTabbedPane1.addTab("TasaNominal", jPanel3);

        jPanel2.setBackground(new java.awt.Color(254, 250, 236));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBox7.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox7.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Trimestral", "Cuatrimestral", "Bimestral", "Diario 360", "Diario 365" }));

        jLabel40.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("TASAS EQUIVALENTES");

        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Tasa equivalente (I EQ) =");

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Tasa nominal (j) =");

        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Frecuencia de capitalizacion (m) =");

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Capitalizacion al año(N) =");

        jComboBox6.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox6.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Trimestral", "Cuatrimestral", "Bimestral", "Diario 360", "Diario 365" }));

        btnCalcularTasaEquivalente.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcularTasaEquivalente.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcularTasaEquivalente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/icons8-calculate-48.png"))); // NOI18N
        btnCalcularTasaEquivalente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTasaEquivalenteActionPerformed(evt);
            }
        });

        txtTasaEquivalente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));

        txtTasaNominalEq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        txtTasaNominalEq.setToolTipText("ingresar % al final");
        txtTasaNominalEq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTasaNominalEqKeyTyped(evt);
            }
        });

        txtFrecuenciaEq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtFrecuenciaEq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrecuenciaEqKeyTyped(evt);
            }
        });

        txtCapitalizacionEq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCapitalizacionEq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapitalizacionEqKeyTyped(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/icons8-emergency-exit-50.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel41)
                                            .addComponent(jLabel42))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTasaNominalEq, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTasaEquivalente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel43)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFrecuenciaEq, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel44)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtCapitalizacionEq, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(btnCalcularTasaEquivalente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel40)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtTasaEquivalente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtTasaNominalEq, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrecuenciaEq, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapitalizacionEq, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularTasaEquivalente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TasaEquivalente", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void btnCalcularTasaEfectivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTasaEfectivaActionPerformed
        double tasaEfectiva = 0.0;
        double tasaNominal = Double.parseDouble(txtTasaNominaljE.getText().replace("%", ""));
        double frecuencia = Double.parseDouble(txtFrecuenciaCapitalizacionE.getText());
//        datos.agregarDatosTasa(tasaEfectiva, tasaNominal, frecuencia);
//        Tasa tasa = new Tasa();
//        tasa.tasaNominal();
        tasaNominal /= 100; 
        tasaEfectiva = Math.pow(((1 + tasaNominal) / frecuencia),
                (frecuencia - 1));

//        txtTasaEfectivaiE.setText(String.valueOf(datos.getTasaEfectiva()).concat("%"));
        txtTasaEfectivaiE.setText(String.valueOf(df.format(tasaEfectiva)).concat("%"));


    }//GEN-LAST:event_btnCalcularTasaEfectivaActionPerformed

    private void btnCalcularTasaEquivalenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTasaEquivalenteActionPerformed
        double tasaEquivalente = 0.0;
        double tasaNominal = Double.parseDouble(txtTasaNominalEq.getText().replace("%", ""));
        double frecuencia = Double.parseDouble(txtFrecuenciaEq.getText());
        double capitalizacion = Double.parseDouble(txtCapitalizacionEq.getText());
        
        tasaNominal /= 100;
        
        tasaEquivalente = capitalizacion * (Math.pow(((1 + tasaNominal) / frecuencia),
                (((frecuencia / capitalizacion) - 1))));
        txtTasaEquivalente.setText(String.valueOf(df.format(tasaEquivalente)).concat("%"));


    }//GEN-LAST:event_btnCalcularTasaEquivalenteActionPerformed

    private void btnCalcularTasaNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTasaNominalActionPerformed
        double tasaEfectiva = Double.parseDouble(tasaEfectivaU.getText().replace("%", ""));
        double tasaNominal = 0.0;
        double frecuencia = Double.parseDouble(frecuenciaU.getText());
        
        tasaEfectiva /= 100;
        
        tasaNominal = tasaEfectiva * (1 + frecuencia * tasaEfectiva);

        tasaNominalU.setText(String.valueOf(df.format(tasaNominal)).concat("%"));

    }//GEN-LAST:event_btnCalcularTasaNominalActionPerformed

    private void txtTasaNominaljEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaNominaljEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaNominaljEActionPerformed

    private void txtFrecuenciaCapitalizacionEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrecuenciaCapitalizacionEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrecuenciaCapitalizacionEActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void txtTasaEfectivaiEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTasaEfectivaiEKeyTyped
        
    }//GEN-LAST:event_txtTasaEfectivaiEKeyTyped

    private void txtTasaNominaljEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTasaNominaljEKeyTyped
        validar.numberKeyTasa(evt, txtTasaNominaljE);
    }//GEN-LAST:event_txtTasaNominaljEKeyTyped

    private void txtFrecuenciaCapitalizacionEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecuenciaCapitalizacionEKeyTyped
        validar.numberDecimalKeyPress(evt, txtFrecuenciaCapitalizacionE);
    }//GEN-LAST:event_txtFrecuenciaCapitalizacionEKeyTyped

    private void tasaEfectivaUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tasaEfectivaUKeyTyped
        validar.numberKeyTasa(evt, tasaNominalU);
    }//GEN-LAST:event_tasaEfectivaUKeyTyped

    private void frecuenciaUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frecuenciaUKeyTyped
        validar.numberDecimalKeyPress(evt, frecuenciaU);
    }//GEN-LAST:event_frecuenciaUKeyTyped

    private void txtTasaNominalEqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTasaNominalEqKeyTyped
        validar.numberKeyTasa(evt, txtTasaNominalEq);
    }//GEN-LAST:event_txtTasaNominalEqKeyTyped

    private void txtFrecuenciaEqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecuenciaEqKeyTyped
        validar.numberDecimalKeyPress(evt, txtFrecuenciaEq);
    }//GEN-LAST:event_txtFrecuenciaEqKeyTyped

    private void txtCapitalizacionEqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapitalizacionEqKeyTyped
        validar.numberDecimalKeyPress(evt, txtCapitalizacionEq);
    }//GEN-LAST:event_txtCapitalizacionEqKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvTasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvTasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvTasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvTasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvTasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularTasaEfectiva;
    private javax.swing.JButton btnCalcularTasaEquivalente;
    private javax.swing.JButton btnCalcularTasaNominal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JFormattedTextField frecuenciaU;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField tasaEfectivaU;
    private javax.swing.JFormattedTextField tasaNominalU;
    private javax.swing.JFormattedTextField txtCapitalizacionEq;
    private javax.swing.JFormattedTextField txtFrecuenciaCapitalizacionE;
    private javax.swing.JFormattedTextField txtFrecuenciaEq;
    private javax.swing.JFormattedTextField txtTasaEfectivaiE;
    private javax.swing.JFormattedTextField txtTasaEquivalente;
    private javax.swing.JFormattedTextField txtTasaNominalEq;
    private javax.swing.JFormattedTextField txtTasaNominaljE;
    // End of variables declaration//GEN-END:variables
}
