/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.uni.view;

/**
 *
 * @author pc
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        BtnSimple = new javax.swing.JButton();
        BtnCompuesto = new javax.swing.JButton();
        BtnTasas = new javax.swing.JButton();
        BtnAtyuda = new javax.swing.JButton();
        BtnVPresente = new javax.swing.JButton();
        BtnVFuturo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 250, 236));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Titulo.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Sistema de cálculos económicos.");

        BtnSimple.setBackground(new java.awt.Color(255, 255, 255));
        BtnSimple.setForeground(new java.awt.Color(0, 0, 0));
        BtnSimple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/presentacion.png"))); // NOI18N
        BtnSimple.setText("Interes Simple");
        BtnSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpleActionPerformed(evt);
            }
        });

        BtnCompuesto.setBackground(new java.awt.Color(255, 255, 255));
        BtnCompuesto.setForeground(new java.awt.Color(0, 0, 0));
        BtnCompuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/futuro.png"))); // NOI18N
        BtnCompuesto.setText("Interes Compuesto");
        BtnCompuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCompuestoActionPerformed(evt);
            }
        });

        BtnTasas.setBackground(new java.awt.Color(255, 255, 255));
        BtnTasas.setForeground(new java.awt.Color(0, 0, 0));
        BtnTasas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/interes.png"))); // NOI18N
        BtnTasas.setText("Tasas");
        BtnTasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTasasActionPerformed(evt);
            }
        });

        BtnAtyuda.setBackground(new java.awt.Color(255, 255, 255));
        BtnAtyuda.setForeground(new java.awt.Color(0, 0, 0));
        BtnAtyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/ayudar.png"))); // NOI18N
        BtnAtyuda.setText("Ayuda");
        BtnAtyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtyudaActionPerformed(evt);
            }
        });

        BtnVPresente.setBackground(new java.awt.Color(255, 255, 255));
        BtnVPresente.setForeground(new java.awt.Color(0, 0, 0));
        BtnVPresente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/tasa-de-interes.png"))); // NOI18N
        BtnVPresente.setText("Valor Presente");
        BtnVPresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVPresenteActionPerformed(evt);
            }
        });

        BtnVFuturo.setBackground(new java.awt.Color(255, 255, 255));
        BtnVFuturo.setForeground(new java.awt.Color(0, 0, 0));
        BtnVFuturo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/uni/resources/tasa-de-interes (1).png"))); // NOI18N
        BtnVFuturo.setText("Valor Futuro");
        BtnVFuturo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVFuturoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnVPresente, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnCompuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnVFuturo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAtyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTasas, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Titulo)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTasas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCompuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVPresente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVFuturo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAtyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpleActionPerformed
              dispose();
        IntSimple h = new IntSimple();
        h.setVisible(true);
    }//GEN-LAST:event_BtnSimpleActionPerformed

    private void BtnCompuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCompuestoActionPerformed
        dispose();
        IntCompuesto h = new IntCompuesto();
        h.setVisible(true);
    }//GEN-LAST:event_BtnCompuestoActionPerformed

    private void BtnTasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTasasActionPerformed
        dispose();
        ConvTasa t = new ConvTasa();
        t.setVisible(true);

    }//GEN-LAST:event_BtnTasasActionPerformed

    private void BtnAtyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAtyudaActionPerformed

    private void BtnVPresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVPresenteActionPerformed
        dispose();
        ValorPresente h = new ValorPresente();
        h.setVisible(true);
    }//GEN-LAST:event_BtnVPresenteActionPerformed

    private void BtnVFuturoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVFuturoActionPerformed
        dispose();
        ValorFuturo h = new ValorFuturo();
        h.setVisible(true);
    }//GEN-LAST:event_BtnVFuturoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtyuda;
    private javax.swing.JButton BtnCompuesto;
    private javax.swing.JButton BtnSimple;
    private javax.swing.JButton BtnTasas;
    private javax.swing.JButton BtnVFuturo;
    private javax.swing.JButton BtnVPresente;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
