/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.uni.view;

/**
 *
 * @author HP14
 */
public class IntCompuesto extends javax.swing.JFrame {

    /**
     * Creates new form IntCompuesto
     */
    public IntCompuesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblSelecione = new javax.swing.JLabel();
        RadioMonto = new javax.swing.JRadioButton();
        TxtMonto = new javax.swing.JTextField();
        RadioCapital = new javax.swing.JRadioButton();
        TxtCapital = new javax.swing.JTextField();
        RadioTasa = new javax.swing.JRadioButton();
        TxtTasa = new javax.swing.JTextField();
        LblCapítalizacion = new javax.swing.JLabel();
        RadioPeriodo = new javax.swing.JRadioButton();
        TxtPeriodo = new javax.swing.JTextField();
        BtnSalir = new javax.swing.JButton();
        BtnCalcular = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        CmbPerido = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(153, 153, 255));
        JPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        LblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo.setText("Interes Compuesto");

        LblSelecione.setForeground(new java.awt.Color(0, 0, 0));
        LblSelecione.setText("Seleccione que variable a calcular.");

        RadioMonto.setForeground(new java.awt.Color(0, 0, 0));
        RadioMonto.setText("Monto");
        RadioMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMontoActionPerformed(evt);
            }
        });

        TxtMonto.setBackground(new java.awt.Color(255, 255, 255));
        TxtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMontoActionPerformed(evt);
            }
        });

        RadioCapital.setForeground(new java.awt.Color(0, 0, 0));
        RadioCapital.setText("Capital");
        RadioCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCapitalActionPerformed(evt);
            }
        });

        TxtCapital.setBackground(new java.awt.Color(255, 255, 255));

        RadioTasa.setForeground(new java.awt.Color(0, 0, 0));
        RadioTasa.setText("Tasa");

        TxtTasa.setBackground(new java.awt.Color(255, 255, 255));
        TxtTasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTasaActionPerformed(evt);
            }
        });

        LblCapítalizacion.setBackground(new java.awt.Color(0, 0, 0));
        LblCapítalizacion.setForeground(new java.awt.Color(0, 0, 0));
        LblCapítalizacion.setText("Capitalizable");

        RadioPeriodo.setForeground(new java.awt.Color(0, 0, 0));
        RadioPeriodo.setText("Período");
        RadioPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPeriodoActionPerformed(evt);
            }
        });

        TxtPeriodo.setBackground(new java.awt.Color(255, 255, 255));

        BtnSalir.setBackground(new java.awt.Color(255, 255, 255));
        BtnSalir.setForeground(new java.awt.Color(0, 0, 0));
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnCalcular.setBackground(new java.awt.Color(255, 255, 255));
        BtnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        BtnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BtnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        BtnLimpiar.setText("Limpiar");

        CmbPerido.setForeground(new java.awt.Color(0, 0, 0));
        CmbPerido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Años ", "Meses", "Semestres ", "Trimestres", "Cuatrimestres", "Bimestres ", "Días 360", "Días 365" }));

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(LblTitulo))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(LblSelecione)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RadioPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addComponent(TxtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LblCapítalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addComponent(TxtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CmbPerido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(BtnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(BtnCalcular)
                .addGap(128, 128, 128)
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(LblTitulo)
                .addGap(31, 31, 31)
                .addComponent(LblSelecione)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioMonto)
                            .addComponent(TxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioCapital)
                            .addComponent(TxtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioTasa)
                            .addComponent(TxtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblCapítalizacion))
                        .addGap(33, 33, 33)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioPeriodo)
                            .addComponent(TxtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CmbPerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 115, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCalcular)
                            .addComponent(BtnSalir)
                            .addComponent(BtnLimpiar))
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RadioMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioMontoActionPerformed

    private void TxtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMontoActionPerformed

    private void RadioCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCapitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioCapitalActionPerformed

    private void TxtTasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTasaActionPerformed

    private void RadioPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioPeriodoActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        dispose();
        FrmMenu r = new FrmMenu();
        r.setVisible(true);  
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntCompuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntCompuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntCompuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntCompuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntCompuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<String> CmbPerido;
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel LblCapítalizacion;
    private javax.swing.JLabel LblSelecione;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JRadioButton RadioCapital;
    private javax.swing.JRadioButton RadioMonto;
    private javax.swing.JRadioButton RadioPeriodo;
    private javax.swing.JRadioButton RadioTasa;
    private javax.swing.JTextField TxtCapital;
    private javax.swing.JTextField TxtMonto;
    private javax.swing.JTextField TxtPeriodo;
    private javax.swing.JTextField TxtTasa;
    // End of variables declaration//GEN-END:variables
}
