/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.uni.view;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import proyecto.uni.controller.DatosGenerales;
import proyecto.uni.model.Interes;
import proyecto.uni.model.InteresCompuesto;
import proyecto.uni.model.InteresSimple;
import proyecto.uni.model.Validar;

/**
 *
 *
 */
public class IntCompuesto extends javax.swing.JFrame {

    /**
     * Creates new form IntCompuesto
     */
    private List<JRadioButton> radioButtonsC;
    private List<String> comboBoxC;
    private List<JButton> botonesC;
    private List<JFormattedTextField> textFieldsC;
    private List<JLabel> labelsC;
    private DecimalFormat df;
    private Validar validar;

    DatosGenerales datos = new DatosGenerales();
    double monto = 0;
    double capital = 0;
    double tasa = 0;
    double periodo = 0;

    public IntCompuesto() {
        initComponents();

        comboBoxC = new ArrayList<>();
        radioButtonsC = new ArrayList<>();
        botonesC = new ArrayList<>();
        textFieldsC = new ArrayList<>();
        labelsC = new ArrayList<>();
        df = new DecimalFormat("#,###,###.##");
        validar = new Validar();

        radioButtonsC.add(RadioMonto);
        radioButtonsC.add(RadioCapital);
        radioButtonsC.add(RadioTasa);
        radioButtonsC.add(RadioPeriodo);

        comboBoxC.add(CmbPerido.getItemAt(0));
        comboBoxC.add(CmbPerido.getItemAt(1));
        comboBoxC.add(CmbPerido.getItemAt(2));
        comboBoxC.add(CmbPerido.getItemAt(3));
        comboBoxC.add(CmbPerido.getItemAt(4));
        comboBoxC.add(CmbPerido.getItemAt(5));
        comboBoxC.add(CmbPerido.getItemAt(6));
        comboBoxC.add(CmbPerido.getItemAt(7));

        textFieldsC.add(TxtMonto);
        textFieldsC.add(TxtCapital);
        textFieldsC.add(TxtTasa);
        textFieldsC.add(TxtPeriodo);

        botonesC.add(BtnLimpiar);
        botonesC.add(BtnCalcular);
        botonesC.add(BtnSalir);

        datos.agregarDatos(botonesC, textFieldsC, radioButtonsC, labelsC);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupCompuesto = new javax.swing.ButtonGroup();
        JPanel = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblSelecione = new javax.swing.JLabel();
        RadioMonto = new javax.swing.JRadioButton();
        RadioCapital = new javax.swing.JRadioButton();
        RadioTasa = new javax.swing.JRadioButton();
        LblCapítalizacion = new javax.swing.JLabel();
        RadioPeriodo = new javax.swing.JRadioButton();
        BtnSalir = new javax.swing.JButton();
        BtnCalcular = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        CmbPerido = new javax.swing.JComboBox<>();
        TxtCapital = new javax.swing.JFormattedTextField();
        TxtTasa = new javax.swing.JFormattedTextField();
        TxtMonto = new javax.swing.JFormattedTextField();
        TxtPeriodo = new javax.swing.JFormattedTextField();
        tasaPonerfinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(153, 153, 255));
        JPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        LblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo.setText("Interes Compuesto");

        LblSelecione.setForeground(new java.awt.Color(0, 0, 0));
        LblSelecione.setText("Seleccione que variable a calcular.");

        btGroupCompuesto.add(RadioMonto);
        RadioMonto.setForeground(new java.awt.Color(0, 0, 0));
        RadioMonto.setText("Monto");
        RadioMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMontoActionPerformed(evt);
            }
        });

        btGroupCompuesto.add(RadioCapital);
        RadioCapital.setForeground(new java.awt.Color(0, 0, 0));
        RadioCapital.setText("Capital");
        RadioCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCapitalActionPerformed(evt);
            }
        });

        btGroupCompuesto.add(RadioTasa);
        RadioTasa.setForeground(new java.awt.Color(0, 0, 0));
        RadioTasa.setText("Tasa");
        RadioTasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioTasaActionPerformed(evt);
            }
        });

        LblCapítalizacion.setBackground(new java.awt.Color(0, 0, 0));
        LblCapítalizacion.setForeground(new java.awt.Color(0, 0, 0));
        LblCapítalizacion.setText("Capitalizable");

        btGroupCompuesto.add(RadioPeriodo);
        RadioPeriodo.setForeground(new java.awt.Color(0, 0, 0));
        RadioPeriodo.setText("Período");
        RadioPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPeriodoActionPerformed(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(255, 255, 255));
        BtnSalir.setForeground(new java.awt.Color(0, 0, 0));
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnCalcular.setBackground(new java.awt.Color(255, 255, 255));
        BtnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        BtnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BtnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        CmbPerido.setForeground(new java.awt.Color(0, 0, 0));
        CmbPerido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Años", "Meses", "Semestres", "Trimestres", "Cuatrimestres", "Bimestres", "Dias 360", "Dias 365" }));
        CmbPerido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbPeridoItemStateChanged(evt);
            }
        });
        CmbPerido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbPeridoMouseClicked(evt);
            }
        });
        CmbPerido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbPeridoActionPerformed(evt);
            }
        });

        TxtCapital.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        TxtCapital.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCapitalKeyTyped(evt);
            }
        });

        TxtTasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        TxtTasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtTasaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtTasaMouseExited(evt);
            }
        });
        TxtTasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTasaKeyTyped(evt);
            }
        });

        TxtMonto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        TxtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMontoKeyTyped(evt);
            }
        });

        TxtPeriodo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        TxtPeriodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPeriodoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RadioPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanelLayout.createSequentialGroup()
                                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(JPanelLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(TxtPeriodo))
                                            .addComponent(TxtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JPanelLayout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(CmbPerido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LblCapítalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(JPanelLayout.createSequentialGroup()
                                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TxtCapital)
                                                .addComponent(TxtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                                            .addComponent(tasaPonerfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addComponent(BtnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnCalcular)
                                .addGap(128, 128, 128)
                                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))))
                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPanelLayout.createSequentialGroup()
                            .addGap(229, 229, 229)
                            .addComponent(LblTitulo))
                        .addGroup(JPanelLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(LblSelecione))))
                .addContainerGap())
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(LblTitulo)
                .addGap(31, 31, 31)
                .addComponent(LblSelecione)
                .addGap(26, 26, 26)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioMonto)
                    .addComponent(TxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioCapital)
                    .addComponent(TxtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioTasa)
                    .addComponent(CmbPerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasaPonerfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioPeriodo)
                    .addComponent(LblCapítalizacion)
                    .addComponent(TxtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCalcular)
                    .addComponent(BtnSalir)
                    .addComponent(BtnLimpiar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RadioMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMontoActionPerformed
        if (radioButtonsC.get(0).isSelected()) {
            TxtMonto.setEnabled(false);
            TxtPeriodo.setEnabled(true);
            TxtCapital.setEnabled(true);
            TxtTasa.setEnabled(true);
        }
    }//GEN-LAST:event_RadioMontoActionPerformed

    private void RadioCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCapitalActionPerformed
        if (radioButtonsC.get(1).isSelected()) {
            TxtCapital.setEnabled(false);
            TxtPeriodo.setEnabled(true);
            TxtMonto.setEnabled(true);
            TxtTasa.setEnabled(true);
        }
    }//GEN-LAST:event_RadioCapitalActionPerformed

    private void RadioPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioPeriodoActionPerformed
        if (radioButtonsC.get(3).isSelected()) {
            TxtPeriodo.setEnabled(false);
            TxtMonto.setEnabled(true);
            TxtCapital.setEnabled(true);
            TxtTasa.setEnabled(true);
        }


    }//GEN-LAST:event_RadioPeriodoActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        dispose();
        FrmMenu r = new FrmMenu();
        r.setVisible(true);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        if (radioButtonsC.get(0).isSelected()) {
            capital = Double.parseDouble(TxtCapital.getText().replace(",", ""));
            tasa = Double.parseDouble(TxtTasa.getText().replace("%", ""));
            periodo = Double.parseDouble(TxtPeriodo.getText().replace(",", ""));
            InteresCompuesto ic = new InteresCompuesto(monto, capital, tasa, periodo, radioButtonsC, comboBoxC);
            ic.cICMonto(ic.getCapital(), ic.getTasa(), ic.getPerido());
            TxtMonto.setText(String.valueOf(df.format(ic.getMonto())));
        }

        if (radioButtonsC.get(1).isSelected()) {
            monto = Double.parseDouble(TxtMonto.getText().replace(",", ""));
            tasa = Double.parseDouble(TxtTasa.getText().replace("%", ""));
            periodo = Double.parseDouble(TxtPeriodo.getText().replace(",", ""));
            InteresCompuesto ic = new InteresCompuesto(monto, capital, tasa, periodo, radioButtonsC, comboBoxC);
            ic.cICCapital(ic.getMonto(), ic.getTasa(), ic.getPerido());
            TxtCapital.setText(String.valueOf(df.format(ic.getCapital())));
        }

        if (radioButtonsC.get(2).isSelected()) {
            monto = Double.parseDouble(TxtMonto.getText().replace(",", ""));
            capital = Double.parseDouble(TxtCapital.getText().replace(",", ""));
            periodo = Double.parseDouble(TxtPeriodo.getText().replace(",", ""));
            InteresCompuesto ic = new InteresCompuesto(monto, capital, tasa, periodo, radioButtonsC, comboBoxC);
            ic.cICTasa(ic.getMonto(), ic.getCapital(), ic.getPerido());
            TxtTasa.setText(String.valueOf(df.format(ic.getTasa()).concat("%")));
        }

        if (radioButtonsC.get(3).isSelected()) {
            monto = Double.parseDouble(TxtMonto.getText().replace(",", ""));
            capital = Double.parseDouble(TxtCapital.getText().replace(",", ""));
            tasa = Double.parseDouble(TxtTasa.getText().replace("%", ""));
            InteresCompuesto ic = new InteresCompuesto(monto, capital, tasa, periodo, radioButtonsC, comboBoxC);
            ic.cICPeriodo(ic.getMonto(), ic.getCapital(), ic.getTasa());
            TxtPeriodo.setText(String.valueOf(ic.getPerido()));
        }
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void RadioTasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioTasaActionPerformed
        if (radioButtonsC.get(2).isSelected()) {
            TxtTasa.setEnabled(false);
            TxtMonto.setEnabled(true);
            TxtCapital.setEnabled(true);
            TxtPeriodo.setEnabled(true);
        }
    }//GEN-LAST:event_RadioTasaActionPerformed

    private void CmbPeridoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbPeridoMouseClicked

    }//GEN-LAST:event_CmbPeridoMouseClicked

    private void CmbPeridoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbPeridoItemStateChanged

    }//GEN-LAST:event_CmbPeridoItemStateChanged

    private void CmbPeridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbPeridoActionPerformed

        String debeingresar = "Debe ingresar periodo en ";

        if (CmbPerido.getItemAt(0).equals(CmbPerido.getItemAt(0))) {
            LblCapítalizacion.setText(debeingresar + CmbPerido.getItemAt(0));
        }
        if (CmbPerido.getItemAt(1).equals("Meses")) {
            LblCapítalizacion.setText(debeingresar + CmbPerido.getItemAt(1));
        }
        if (CmbPerido.getItemAt(2).equals("Semestral")) {
            LblCapítalizacion.setText(debeingresar + CmbPerido.getItemAt(2));
        }
        if (CmbPerido.getItemAt(3).equals("Trimestral")) {
            LblCapítalizacion.setText(debeingresar + CmbPerido.getItemAt(3));
        }
        if (CmbPerido.getItemAt(4).equals("Cuatrimestral")) {
            LblCapítalizacion.setText("Debe ingresar periodo en " + CmbPerido.getItemAt(4));
        }
        if (CmbPerido.getItemAt(5).equals("Bimestral")) {
            LblCapítalizacion.setText("Debe ingresar periodo en " + CmbPerido.getItemAt(5));
        }
        if (CmbPerido.getItemAt(6).equals("Dias 360")) {
            LblCapítalizacion.setText("Debe ingresar periodo " + CmbPerido.getItemAt(6));
        }
        if (CmbPerido.getItemAt(7).equals("Dias 365")) {
            LblCapítalizacion.setText("Debe ingresar periodo en " + CmbPerido.getItemAt(7));
        }
    }//GEN-LAST:event_CmbPeridoActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        Interes interesCompuesto = new InteresCompuesto();
        interesCompuesto.limpiar(datos.getTextFieldsIS());
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void TxtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMontoKeyTyped
        validar.numberDecimalKeyPress(evt, TxtMonto);


    }//GEN-LAST:event_TxtMontoKeyTyped

    private void TxtCapitalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCapitalKeyTyped
        validar.numberDecimalKeyPress(evt, TxtCapital);
    }//GEN-LAST:event_TxtCapitalKeyTyped

    private void TxtTasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTasaKeyTyped
        validar.numberKeyTasa(evt, TxtTasa);
    }//GEN-LAST:event_TxtTasaKeyTyped

    private void TxtPeriodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPeriodoKeyTyped
        validar.numberDecimalKeyPress(evt, TxtPeriodo);
        

    }//GEN-LAST:event_TxtPeriodoKeyTyped

    private void TxtTasaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTasaMouseExited
        tasaPonerfinal.setText("");
    }//GEN-LAST:event_TxtTasaMouseExited

    private void TxtTasaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTasaMouseEntered
        tasaPonerfinal.setText("Poner al final %");
    }//GEN-LAST:event_TxtTasaMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntCompuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntCompuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntCompuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntCompuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntCompuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<String> CmbPerido;
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel LblCapítalizacion;
    private javax.swing.JLabel LblSelecione;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JRadioButton RadioCapital;
    private javax.swing.JRadioButton RadioMonto;
    private javax.swing.JRadioButton RadioPeriodo;
    private javax.swing.JRadioButton RadioTasa;
    private javax.swing.JFormattedTextField TxtCapital;
    private javax.swing.JFormattedTextField TxtMonto;
    private javax.swing.JFormattedTextField TxtPeriodo;
    private javax.swing.JFormattedTextField TxtTasa;
    private javax.swing.ButtonGroup btGroupCompuesto;
    private javax.swing.JLabel tasaPonerfinal;
    // End of variables declaration//GEN-END:variables
}
