/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.uni.view;

/**
 *
 * @author HP14
 */
public class ValorPresente extends javax.swing.JFrame {

    /**
     * Creates new form ValorPresente
     */
    public ValorPresente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jVencidas = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblAnualidad = new javax.swing.JLabel();
        TxtAnualidad = new javax.swing.JTextField();
        LblMonto = new javax.swing.JLabel();
        TxtMonto = new javax.swing.JTextField();
        LblTasa = new javax.swing.JLabel();
        TxtTasa = new javax.swing.JTextField();
        LblNPeriodos = new javax.swing.JLabel();
        TxtPeridos = new javax.swing.JTextField();
        LblIngrese = new javax.swing.JLabel();
        TxtTasAd = new javax.swing.JTextField();
        CmbPeriodo = new javax.swing.JComboBox<>();
        BtnCalcular = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        JVencidasM = new javax.swing.JPanel();
        LbMonto = new javax.swing.JLabel();
        TxtMonto2 = new javax.swing.JTextField();
        LBAnualidad = new javax.swing.JLabel();
        TxAnualidad = new javax.swing.JTextField();
        LbTasa = new javax.swing.JLabel();
        TxTasa = new javax.swing.JTextField();
        LbNPeriodos = new javax.swing.JLabel();
        TxPeriodos = new javax.swing.JTextField();
        TxtTasa3 = new javax.swing.JTextField();
        TxtTiempo = new javax.swing.JComboBox<>();
        LblIngreNA = new javax.swing.JLabel();
        BtNCalcular = new javax.swing.JButton();
        BTnLimpiar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        LblAnticipadas = new javax.swing.JLabel();
        LbLAnualidad = new javax.swing.JLabel();
        Txttasa = new javax.swing.JTextField();
        Lblingresen = new javax.swing.JLabel();
        CmbTiempo = new javax.swing.JComboBox<>();
        LBLTasa = new javax.swing.JLabel();
        LBLMonto = new javax.swing.JLabel();
        LBLPeriodos = new javax.swing.JLabel();
        Txtanualidad = new javax.swing.JTextField();
        jTextField98 = new javax.swing.JTextField();
        jTextField99 = new javax.swing.JTextField();
        jTextField100 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jTextField76 = new javax.swing.JTextField();
        jComboBox15 = new javax.swing.JComboBox<>();
        jLabel89 = new javax.swing.JLabel();
        jTextField90 = new javax.swing.JTextField();
        jTextField91 = new javax.swing.JTextField();
        jTextField92 = new javax.swing.JTextField();
        jTextField93 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jVencidas.setBackground(new java.awt.Color(153, 153, 255));
        jVencidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LblTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LblTitulo.setText("Vencidas");

        LblAnualidad.setForeground(new java.awt.Color(0, 0, 0));
        LblAnualidad.setText("Anualidad ");

        TxtAnualidad.setBackground(new java.awt.Color(255, 255, 255));
        TxtAnualidad.setForeground(new java.awt.Color(0, 0, 0));

        LblMonto.setForeground(new java.awt.Color(0, 0, 0));
        LblMonto.setText("Monto ");

        TxtMonto.setBackground(new java.awt.Color(255, 255, 255));
        TxtMonto.setForeground(new java.awt.Color(0, 0, 0));

        LblTasa.setForeground(new java.awt.Color(0, 0, 0));
        LblTasa.setText("Tasa ");

        TxtTasa.setBackground(new java.awt.Color(255, 255, 255));
        TxtTasa.setForeground(new java.awt.Color(0, 0, 0));

        LblNPeriodos.setForeground(new java.awt.Color(0, 0, 0));
        LblNPeriodos.setText("No.Periodos ");

        TxtPeridos.setBackground(new java.awt.Color(255, 255, 255));
        TxtPeridos.setForeground(new java.awt.Color(0, 0, 0));

        LblIngrese.setForeground(new java.awt.Color(0, 0, 0));
        LblIngrese.setText("Ingrese n en años\t ");

        TxtTasAd.setBackground(new java.awt.Color(255, 255, 255));
        TxtTasAd.setForeground(new java.awt.Color(0, 0, 0));

        CmbPeriodo.setBackground(new java.awt.Color(255, 255, 255));
        CmbPeriodo.setForeground(new java.awt.Color(0, 0, 0));
        CmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Trimestral", "Cuatrimestral", "Bimestral", "Diario 360", "Diario 365" }));

        BtnCalcular.setBackground(new java.awt.Color(255, 255, 255));
        BtnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        BtnCalcular.setText("Calcular");

        BtnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BtnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jVencidasLayout = new javax.swing.GroupLayout(jVencidas);
        jVencidas.setLayout(jVencidasLayout);
        jVencidasLayout.setHorizontalGroup(
            jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jVencidasLayout.createSequentialGroup()
                .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jVencidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jVencidasLayout.createSequentialGroup()
                                .addComponent(LblTasa)
                                .addGap(142, 142, 142)
                                .addComponent(TxtTasAd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(CmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jVencidasLayout.createSequentialGroup()
                                .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jVencidasLayout.createSequentialGroup()
                                        .addComponent(LblNPeriodos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtPeridos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jVencidasLayout.createSequentialGroup()
                                        .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblAnualidad)
                                            .addComponent(LblMonto))
                                        .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jVencidasLayout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(TxtAnualidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jVencidasLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TxtMonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TxtTasa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(1, 1, 1)
                                .addComponent(LblIngrese))))
                    .addGroup(jVencidasLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(BtnCalcular)
                        .addGap(64, 64, 64)
                        .addComponent(BtnLimpiar))
                    .addGroup(jVencidasLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(LblTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jVencidasLayout.setVerticalGroup(
            jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jVencidasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblAnualidad)
                    .addComponent(TxtAnualidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMonto)
                    .addComponent(TxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTasa)
                    .addComponent(TxtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTasAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNPeriodos)
                    .addComponent(TxtPeridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblIngrese))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jVencidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCalcular)
                    .addComponent(BtnLimpiar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        JVencidasM.setBackground(new java.awt.Color(153, 153, 255));
        JVencidasM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LbMonto.setForeground(new java.awt.Color(0, 0, 0));
        LbMonto.setText("Monto ");

        TxtMonto2.setBackground(new java.awt.Color(255, 255, 255));
        TxtMonto2.setForeground(new java.awt.Color(0, 0, 0));

        LBAnualidad.setForeground(new java.awt.Color(0, 0, 0));
        LBAnualidad.setText("Anualidad ");

        TxAnualidad.setBackground(new java.awt.Color(255, 255, 255));
        TxAnualidad.setForeground(new java.awt.Color(0, 0, 0));

        LbTasa.setForeground(new java.awt.Color(0, 0, 0));
        LbTasa.setText("Tasa ");

        TxTasa.setBackground(new java.awt.Color(255, 255, 255));
        TxTasa.setForeground(new java.awt.Color(0, 0, 0));

        LbNPeriodos.setForeground(new java.awt.Color(0, 0, 0));
        LbNPeriodos.setText("No.Periodos ");

        TxPeriodos.setBackground(new java.awt.Color(255, 255, 255));
        TxPeriodos.setForeground(new java.awt.Color(0, 0, 0));

        TxtTasa3.setBackground(new java.awt.Color(255, 255, 255));
        TxtTasa3.setForeground(new java.awt.Color(0, 0, 0));

        TxtTiempo.setBackground(new java.awt.Color(255, 255, 255));
        TxtTiempo.setForeground(new java.awt.Color(0, 0, 0));
        TxtTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Trimestral", "Cuatrimestral", "Bimestral", "Diario 360", "Diario 365" }));

        LblIngreNA.setForeground(new java.awt.Color(0, 0, 0));
        LblIngreNA.setText("Ingrese n en años\t ");

        BtNCalcular.setBackground(new java.awt.Color(255, 255, 255));
        BtNCalcular.setForeground(new java.awt.Color(0, 0, 0));
        BtNCalcular.setText("Calcular");

        BTnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BTnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        BTnLimpiar.setText("Limpiar");
        BTnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JVencidasMLayout = new javax.swing.GroupLayout(JVencidasM);
        JVencidasM.setLayout(JVencidasMLayout);
        JVencidasMLayout.setHorizontalGroup(
            JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JVencidasMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JVencidasMLayout.createSequentialGroup()
                        .addComponent(BtNCalcular)
                        .addGap(120, 120, 120)
                        .addComponent(BTnLimpiar))
                    .addGroup(JVencidasMLayout.createSequentialGroup()
                        .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(JVencidasMLayout.createSequentialGroup()
                                .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(JVencidasMLayout.createSequentialGroup()
                                        .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBAnualidad)
                                            .addComponent(LbTasa))
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JVencidasMLayout.createSequentialGroup()
                                        .addComponent(LbNPeriodos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxTasa)
                                    .addComponent(TxPeriodos)
                                    .addComponent(TxAnualidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JVencidasMLayout.createSequentialGroup()
                                .addComponent(LbMonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblIngreNA)
                            .addGroup(JVencidasMLayout.createSequentialGroup()
                                .addComponent(TxtTasa3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JVencidasMLayout.setVerticalGroup(
            JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JVencidasMLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbMonto)
                    .addComponent(TxtMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBAnualidad)
                    .addComponent(TxAnualidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JVencidasMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbTasa)
                            .addComponent(TxTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTasa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(JVencidasMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbNPeriodos)
                            .addComponent(TxPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblIngreNA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTnLimpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JVencidasMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtNCalcular)
                        .addGap(26, 26, 26))))
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LblAnticipadas.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LblAnticipadas.setForeground(new java.awt.Color(0, 0, 0));
        LblAnticipadas.setText("Anticipadas");

        LbLAnualidad.setForeground(new java.awt.Color(0, 0, 0));
        LbLAnualidad.setText("Anualidad ");

        Txttasa.setBackground(new java.awt.Color(255, 255, 255));
        Txttasa.setForeground(new java.awt.Color(0, 0, 0));

        Lblingresen.setForeground(new java.awt.Color(0, 0, 0));
        Lblingresen.setText("Ingrese n en años\t ");

        CmbTiempo.setBackground(new java.awt.Color(255, 255, 255));
        CmbTiempo.setForeground(new java.awt.Color(0, 0, 0));
        CmbTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Trimestral", "Cuatrimestral", "Bimestral", "Diario 360", "Diario 365" }));

        LBLTasa.setForeground(new java.awt.Color(0, 0, 0));
        LBLTasa.setText("Tasa ");

        LBLMonto.setForeground(new java.awt.Color(0, 0, 0));
        LBLMonto.setText("Monto ");

        LBLPeriodos.setForeground(new java.awt.Color(0, 0, 0));
        LBLPeriodos.setText("No.Periodos ");

        Txtanualidad.setBackground(new java.awt.Color(255, 255, 255));
        Txtanualidad.setForeground(new java.awt.Color(0, 0, 0));
        Txtanualidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtanualidadActionPerformed(evt);
            }
        });

        jTextField98.setBackground(new java.awt.Color(255, 255, 255));
        jTextField98.setForeground(new java.awt.Color(0, 0, 0));

        jTextField99.setBackground(new java.awt.Color(255, 255, 255));
        jTextField99.setForeground(new java.awt.Color(0, 0, 0));

        jTextField100.setBackground(new java.awt.Color(255, 255, 255));
        jTextField100.setForeground(new java.awt.Color(0, 0, 0));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setText("Calcular");

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setForeground(new java.awt.Color(0, 0, 0));
        jButton15.setText("Limpiar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLTasa)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbLAnualidad)
                                    .addComponent(LBLMonto))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txtanualidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField98, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField99, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField100, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LBLPeriodos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(Txttasa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CmbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(Lblingresen)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton14)
                        .addGap(64, 64, 64)
                        .addComponent(jButton15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblAnticipadas)
                .addGap(145, 145, 145))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LblAnticipadas)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbLAnualidad)
                    .addComponent(Txtanualidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLMonto)
                    .addComponent(jTextField98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTasa)
                    .addComponent(jTextField99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txttasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLPeriodos)
                    .addComponent(jTextField100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lblingresen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel85.setForeground(new java.awt.Color(0, 0, 0));
        jLabel85.setText("Monto ");

        jLabel86.setForeground(new java.awt.Color(0, 0, 0));
        jLabel86.setText("Anualidad ");

        jLabel87.setForeground(new java.awt.Color(0, 0, 0));
        jLabel87.setText("Tasa ");

        jLabel88.setForeground(new java.awt.Color(0, 0, 0));
        jLabel88.setText("No.Periodos ");

        jTextField76.setBackground(new java.awt.Color(255, 255, 255));
        jTextField76.setForeground(new java.awt.Color(0, 0, 0));

        jComboBox15.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox15.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Trimestral", "Cuatrimestral", "Bimestral", "Diario 360", "Diario 365" }));

        jLabel89.setForeground(new java.awt.Color(0, 0, 0));
        jLabel89.setText("Ingrese n en años\t ");

        jTextField90.setBackground(new java.awt.Color(255, 255, 255));
        jTextField90.setForeground(new java.awt.Color(0, 0, 0));

        jTextField91.setBackground(new java.awt.Color(255, 255, 255));
        jTextField91.setForeground(new java.awt.Color(0, 0, 0));

        jTextField92.setBackground(new java.awt.Color(255, 255, 255));
        jTextField92.setForeground(new java.awt.Color(0, 0, 0));

        jTextField93.setBackground(new java.awt.Color(255, 255, 255));
        jTextField93.setForeground(new java.awt.Color(0, 0, 0));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Calcular");

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Limpiar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("Salir");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel86)
                                            .addComponent(jLabel87))
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel88)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField92)
                                    .addComponent(jTextField93)
                                    .addComponent(jTextField91, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel85)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField90, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton10)))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel89)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jButton11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(jTextField90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(jTextField91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(jTextField92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88)
                    .addComponent(jTextField93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel89))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JVencidasM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jVencidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jVencidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JVencidasM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BTnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTnLimpiarActionPerformed

    private void TxtanualidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtanualidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtanualidadActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        dispose();
        FrmMenu r = new FrmMenu();
        r.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValorPresente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValorPresente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValorPresente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValorPresente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValorPresente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTnLimpiar;
    private javax.swing.JButton BtNCalcular;
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JComboBox<String> CmbPeriodo;
    private javax.swing.JComboBox<String> CmbTiempo;
    private javax.swing.JPanel JVencidasM;
    private javax.swing.JLabel LBAnualidad;
    private javax.swing.JLabel LBLMonto;
    private javax.swing.JLabel LBLPeriodos;
    private javax.swing.JLabel LBLTasa;
    private javax.swing.JLabel LbLAnualidad;
    private javax.swing.JLabel LbMonto;
    private javax.swing.JLabel LbNPeriodos;
    private javax.swing.JLabel LbTasa;
    private javax.swing.JLabel LblAnticipadas;
    private javax.swing.JLabel LblAnualidad;
    private javax.swing.JLabel LblIngreNA;
    private javax.swing.JLabel LblIngrese;
    private javax.swing.JLabel LblMonto;
    private javax.swing.JLabel LblNPeriodos;
    private javax.swing.JLabel LblTasa;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel Lblingresen;
    private javax.swing.JTextField TxAnualidad;
    private javax.swing.JTextField TxPeriodos;
    private javax.swing.JTextField TxTasa;
    private javax.swing.JTextField TxtAnualidad;
    private javax.swing.JTextField TxtMonto;
    private javax.swing.JTextField TxtMonto2;
    private javax.swing.JTextField TxtPeridos;
    private javax.swing.JTextField TxtTasAd;
    private javax.swing.JTextField TxtTasa;
    private javax.swing.JTextField TxtTasa3;
    private javax.swing.JComboBox<String> TxtTiempo;
    private javax.swing.JTextField Txtanualidad;
    private javax.swing.JTextField Txttasa;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField100;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField90;
    private javax.swing.JTextField jTextField91;
    private javax.swing.JTextField jTextField92;
    private javax.swing.JTextField jTextField93;
    private javax.swing.JTextField jTextField98;
    private javax.swing.JTextField jTextField99;
    private javax.swing.JPanel jVencidas;
    // End of variables declaration//GEN-END:variables
}
